[package]
name = "GeneralPlotter"
version = "0.1.0"
edition = "2024"

[dependencies]

egui = { version = "0.32.3", features = ["color-hex"] }
egui_extras = { version = "0.32.3", features = ["image", "svg"] }
eframe = "0.32.3"
egui_plot = "0.33.0"
serialport = "4.8.1"
image = "0.25.8"
